# Generated by Django 5.1 on 2024-08-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postFeed',
            fields=[
                ('postFeedId', models.AutoField(primary_key=True, serialize=False)),
                ('postContent', models.TextField(max_length=500)),
                ('imageUploaded', models.ImageField(upload_to='upload_images/')),
            ],
        ),
    ]
