# Generated by Django 5.1 on 2024-08-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_pricingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingmodel',
            name='image',
            field=models.ImageField(upload_to='pricingProduct/'),
        ),
    ]
