# Generated by Django 5.1 on 2024-08-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_clientsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=800)),
            ],
        ),
    ]
